### ISSUE TITLE
**Help** Trying to configure utility on Fedora 37 Workstation

### ISSUE THREAD

**Issue by 0xSDX** [liperium/Linux-Conservation-Mode-Utility#3]
Trying to configure the utility on my laptop running fedora 37.

> `./TrayConservationMode: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory`

Any help to setup the utility is appreciated !

**Comment by liperium** [comment]
If you installed it with the install.sh, when it asks if you want to install the legacy version, say yes!
If you installed it manually, just download the legacy version instead!

**Comment by dswapnil104** [comment]
@liperium hey mate !
Yes I did try installing manually and did chose legacy .*tar.gz from latest release and this was the prompt error shown.

> `./TrayConservationMode: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory`

**Comment by liperium** [comment]
Is this ok for you? I can't see your response here, but have gotten an email :octocat:

**Comment by 0xSDX** [comment]
## Goodnote : 
### Anyone trying this utility on GNOME 43 (in my case fedora37)

Make sure to chose **Legacy** release package i.e:
> [TrayConservationMode_Legacy.tar.gz](https://github.com/liperium/Linux-Conservation-Mode-Utility/releases/download/v.1.1-beta/TrayConservationMode_Legacy.tar.gz)

Look for the dependencies to be installed i.e :
- `libappindicator-gtk3`
- [gnome-shell-extension-appindicator](https://github.com/ubuntu/gnome-shell-extension-appindicator)
   - Install using:
     1. [Gnome Extension Store](https://extensions.gnome.org/extension/615/appindicator-support/)
     2. Or fire up a command like I did , as apparently extensions website sometimes fails to perform a dependency check:
         - `sudo dnf install gnome-shell-extension-appindicator` (apt if on Debian based)

**Comment by 0xSDX** [comment]
> Is this ok for you? I can't see your response here, but have gotten an email :octocat:


I deleted a stale comment sorry for the mail ping.
I fixed the issue, thanks for a prompt reply.
I was wondering what is correct way of adding this utility to `.desktop` application list as well as setting it up as `startup application`, any help on this front ?

**Comment by liperium** [comment]
> 

Yes this would be the correct way to do it ( at least, that's the way I do it )
Hope you like the tool 👍 
I was running Fedora too and never had the problem, thanks for the info on the dependancy 😄

**Comment by liperium** [comment]
I added your comment to the readme of the application! Have a good one!

**Comment by 0xSDX** [comment]
> Yes this would be the correct way to do it ( at least, that's the way I do it ) Hope you like the tool +1 I was running Fedora too and never had the problem, thanks for the info on the dependency smile

Firstly, I truly love the utility !! Thanks for making it.
But I'm afraid you lost me with the previous comment. I am not sure as to how do I make a `.desktop` file such that it starts up on boot as a `startup-application`, I was wondering if you could help me with same, just the way you mention you had done it on your Fedora ride...

**Comment by liperium** [comment]
I think I used Alacarte utility to add a desktop entry, you can look online to do it manually, basically you have to link it to the TrayConservationMode file.

**Comment by 0xSDX** [comment]
> I think I used Alacarte utility to add a desktop entry, you can look online to do it manually, basically you have to link it to the TrayConservationMode file.

I would like to know what contents went into the `.desktop` file generated. Last time I tried I had startup issues with utility configured.

**Comment by liperium** [comment]
Sorry for the **REALLY** late response, but I just did it on a new system, here is mine ( replace %USER% with what yours ) : 
```
[Desktop Entry]
Comment=
Exec=/home/%USER%/Documents/TCM/TrayConservationMode
GenericName=Tray conservation mode manager for Lenovo laptops\s
Icon=/home/%USER%/Documents/TCM/assets/iconOn.ico
Name=Tray Conservation Mode
NoDisplay=false
Terminal=false
Type=Application
```
