### ISSUE TITLE
Add a separate notice for distributions that do not use the wheel user group

### ISSUE THREAD

**Issue by Anvith00** [liperium/Linux-Conservation-Mode-Utility#4]
Greetings, @liperium.
This is one little yet a very useful power conservation tool for Linux. I have been using it (you'll be surprised to learn that this works on quite a lot of Lenovo devices haha :slightly_smiling_face: ) on my 2021 Ideapad 5 (15ITL05) for a long time on Fedora, until recently I had enough of certain issues that the bleeding and leading edge kernel releases were bringing, which is why I switched to Linux Mint 21.1. And I noticed, the thing is, Debian and its derivatives do not use `wheel` by default, and although possible to enable it, I did not bother changing it.

What I did instead was simply replacing the text "wheel" with "sudo" in the line
```bash
%sudo ALL=(ALL) NOPASSWD: /usr/bin/tee /sys/bus/platform/drivers/ideapad_acpi/VPC2004\:00/conservation_mode
```
which does the trick of making it work on distributions that do not use wheel. I have personally encountered some beginner Linux + Lenovo notebook users who were stuck at the "sudo visudo" instruction segment since they were using a Debian based distribution (Ubuntu). Based on that experience, I would like to propose to you on reflecting these changes in your "manual installation" section to make it easier for beginner Linux users using Debian derivatives, something like this perhaps:

(Draft)
> :warning: **NOTICE:** If you are using any Debian based Linux distributions (Ubuntu/ Zorin/ Linux Mint/ Pop_OS!/ KDE Neon/ Elementary OS and many more), or a distribution that does not have the `wheel` user group enabled by default, replace **%wheel** in the beginning of the line with **%sudo** as follows :point_down: :
>```bash
>%sudo ALL=(ALL) NOPASSWD: /usr/bin/tee /sys/bus/platform/drivers/ideapad_acpi/VPC2004\:00/conservation_mode```

**Comment by liperium** [comment]
**Good catch.** Really appreciate the post and the time you took to write it.

I just added the fix where the appended text to visudo is mentionned. I wouldn't like to add another "section" just to mention the fix.

_In a future update, I'd like to package the app for different distros, simply to make sure it has the best compatibility or fixes for most distros. But I'd need to install different distros and don't feel like doing it right now._

As I said earlier, thanks for the input and I'm happy this utility has found some users!🥳
Take care.
